server:
  port: 8081

spring:
  application:
    name: kafka-learn
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "am.learn.kafka.common,am.learn.kafka.*"
    listener:
      missing-topics-fatal: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  pattern:
    level: "%5p [%X{correlationId:-}]"
  level:
    am.learn.kafka: INFO
    org.apache.kafka: WARN
    org.apache.kafka.clients.NetworkClient: ERROR
