server:
  port: 8082

spring:
  application:
    name: rabbit-learn
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  pattern:
    level: "%5p [%X{correlationId:-}]"
  level:
    am.learn.rabbit: INFO
    org.springframework.amqp: WARN
